---
services:
  pyload:
    image: linuxserver/pyload-ng:latest
    container_name: pyload-ng
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    volumes:
      - ~/docker_volumes/pyload_config:/config
      - ~/Downloads:/downloads
    ports:
      - 8000:8000
      - 9666:9666
    restart: unless-stopped